### ISSUE TITLE
好几天没更新了

### ISSUE THREAD

**Issue by hui6900** [dai-pch/2019-nCoV-Fit#2]
支持GPU运算吗？用CPU要计算好久，不知作者用的是什么设备运算的。

**Comment by dai-pch** [comment]
我自己yongpython写的搜索算法，不支持gpu运算。
26号数据出来之后我没找到合适的拟合结果，不可靠的结果显示最终感染人数已经突破10w，我认为这个不太可能，所以就没再更新。
你要有兴趣可以补充一些数据再跑一下。
sir模型在我的笔记本电脑上都可以算，但是seir模型一直没有足够的算力，所以没有结果。
