### ISSUE TITLE
运行效率

### ISSUE THREAD

**Issue by cunyizju** [dai-pch/2019-nCoV-Fit#3]
请问您那边运行模型一次要多久？我手头电脑配置虽然低，但感觉也不至于半个小时没结果吧。。

**Comment by dai-pch** [comment]
只跑sir模型的话，我的笔记本单线程运行一次大概要3、4个小时；在服务器上16线程跑大约10分钟。seir模型耗时很长，我也没有跑出结果。

**Comment by xhwhht** [comment]
您好 想问一下您的电脑什么配置

**Comment by cunyizju** [comment]
SIR模型我用了不到半小时，具体时间没记。SEIR模型已放弃。电脑配置：Intel(R) Core(TM) i5-2450M CPU @2.50GHz 2.50 GHz 8 GB。
我用matlab编写一段分段SEIR代码: https://github.com/cunyizju/phase-field-modelling/tree/master/nCov-prediction，欢迎一起维护~

**Comment by dai-pch** [comment]
> 您好 想问一下您的电脑什么配置

我的笔记本是i5-6200U。

**Comment by dai-pch** [comment]
> SIR模型我用了不到半小时，具体时间没记。SEIR模型已放弃。电脑配置：Intel(R) Core(TM) i5-2450M CPU @2.50GHz 2.50 GHz 8 GB。
> 我用matlab编写一段分段SEIR代码: [https://github.com/cunyizju/phase-field-modelling/tree/master/nCov-prediction，欢迎一起维护](https://github.com/cunyizju/phase-field-modelling/tree/master/nCov-prediction%EF%BC%8C%E6%AC%A2%E8%BF%8E%E4%B8%80%E8%B5%B7%E7%BB%B4%E6%8A%A4)~

哈哈，我去看看。
